In [2]:
# pivot tables

In [3]:
import numpy as np
import pandas as pd

In [14]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': [
        'East', 'West', 'North', 'South']* 5,
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': [
        'John', 'Mary', 'Bob', 'Alice']*5
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    365     74   John  January      Q1
1  2023-01-02       B   West    557     27   Mary  January      Q1
2  2023-01-03       C  North    538     14    Bob  January      Q1
3  2023-01-04       D  South    475     56  Alice  January      Q1
4  2023-01-05       A   East    515     76   John  January      Q1
5  2023-01-06       B   West    664     74   Mary  January      Q1
6  2023-01-07       C  North    702     84    Bob  January      Q1
7  2023-01-08       D  South    813     39  Alice  January      Q1
8  2023-01-09       A   East    424     36   John  January      Q1
9  2023-01-10       B   West    428     47   Mary  January      Q1
10 2023-01-11       C  North    766     32    Bob  January      Q1
11 2023-01-12       D  South    848     54  Alice  January      Q1
12 2023-01-13       A   East    965     91   John  January      Q1
13 2023-01-14       B   West    933     24   Mary  January      Q1
14 2023-01-15       C  North    436     40    Bob  January      Q1
15 2023-01-16       D  South    365     76  Alice  January      Q1
16 2023-01-17       A   East    316     52   John  January      Q1
17 2023-01-18       B   West    264     89   Mary  January      Q1
18 2023-01-19       C  North    882     40    Bob  January      Q1
19 2023-01-20       D  South    133     46  Alice  January      Q1

In [17]:
pd.pivot_table(df,values="Sales",index = "Product",columns="Region",aggfunc="sum")

Region     East   North   South    West
Product
A        2585.0     NaN     NaN     NaN
B           NaN     NaN     NaN  2846.0
C           NaN  3324.0     NaN     NaN
D           NaN     NaN  2634.0     NaN

In [20]:
## Multiple indexes

pd.pivot_table(df,values=["Sales","Units"],index="Product",columns="Region",aggfunc="max",fill_value=0)

        Sales                  Units
Region   East North South West  East North South West
Product
A         965     0     0    0    91     0     0    0
B           0     0     0  933     0     0     0   89
C           0   882     0    0     0    84     0    0
D           0     0   848    0     0     0    76    0

In [21]:
## groupby and pivot tables provide same results and calculations
## groupby is best for calculations and pivott tables are excellent for representing that data in tables